### ISSUE TITLE
Error: WireGuard interface failed to come 'up', exit code is '1'

### ISSUE THREAD

**Issue by peter-samuel96** [binhex/arch-qbittorrentvpn#127]
I'm using `binhex/arch-qbittorrentvpn` using the latest tag. 

Machine Specs: Ubuntu 18.04.6 LTS and kernel Linux 5.4.0-97-generic

Here is link to the supervisord.log as requested: https://pastebin.com/h9KY61Ac

Thank you!

**Comment by r0arkin** [comment]
I'm running a different Linux distro then yours but the issue is the same. I had to specify where /lib/modules was located to get it to work. So under volumes I added `- /lib/modules:/lib/modules`. Let me know if that helps!

**Comment by brazyptian96** [comment]
First, thanks for the quick response. 

> So I think you have a few problems here.
> 
> I see:
> 
> ```
> 2022-02-08 15:32:48,082 DEBG 'start-script' stderr output:
> [#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
>  
> 2022-02-08 15:32:48,083 DEBG 'start-script' stderr output:
> sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"
> ```
> 

I tried running the docker container as privileged and still ran into this error.

> and then the lib/modules issue.
> 
> To fix the /lib/modules issue I had to specify where /lib/modules was located. So under volumes I added `- /lib/modules:/lib/modules`.
> 

Would I place this under volumes? I'm using Portainer to manage the docker container.

> Can you paste your docker-compose or docker run?

Here is my yaml file: https://pastebin.com/HGzzTRbp

I'm using PlexGuide for my setup.

**Comment by brazyptian96** [comment]
Wow, my reading skills are failing me. I'm adding it to volumes now.....

**Comment by r0arkin** [comment]
> Wow, my reading skills are failing me. I'm adding it to volumes now.....

Heh, all good.

I'm not too sure about pertainer since I've used it once way in the beginning but, this is my docker-compose so you can base it off of that:

```
version: "3.7"

services:
  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn:4.3.9-2-01
    #image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrentvpn
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      - traefik
    ports:
      - 8383:8383
    volumes:
      - ${USERDIR}/assets/qbittorrentvpn/config:/config
      - /mnt/downloads:/data
      - /mnt/media:/media
      - /etc/localtime:/etc/localtime:ro
      - /lib/modules:/lib/modules
    env_file: ${USERDIR}/assets/qbittorrentvpn/qbittorrentvpn.env
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrentvpn-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrentvpn-rtr.rule=Host(`qbit.${DOMAINNAME}`)"
      - "traefik.http.routers.qbittorrentvpn-rtr.tls=true"
      - "traefik.http.routers.qbittorrentvpn-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.qbittorrentvpn-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrentvpn-rtr.service=qbittorrentvpn-svc"
      - "traefik.http.services.qbittorrentvpn-svc.loadbalancer.server.port=8383"

networks:
  traefik:
    name: traefik
    external: true
```
