### ISSUE TITLE
torrent save path changes on every container restart

### ISSUE THREAD

**Issue by guillaumedsde** [binhex/arch-qbittorrentvpn#2]
hi again,

I'm having another issue, on every container restart, the torrent save path changes to `/config/qBittorrent/` and automatic torrent management is turned off, I'm unsure as to what could be causing this.

**Comment by guillaumedsde** [comment]
I've researched the problem a bit more:

I've written a docker-compose file in order to make the problem (mabye?) repoducible elsewhere (see below)

and upon launching the compose file, qbittorrent immediatly moves all torrents (see logs below)



## docker-compose.yml

```yaml
version: "3.4"

x-https: &https
  VIRTUAL_PROTO: http
  HTTPS_METHOD: redirect
  LETSENCRYPT_EMAIL: ${letsencrypt_email}
  SSL_POLICY: Mozilla-Modern

x-restart: &restart
  restart: on-failure:5

services:
    # nginx reverse proxy container
    # binds to HTTP (80) and HTTPS (443) ports
    # then serves requests as a reverse proxy to the different containers defined below
    nginx-proxy:
      image: jwilder/nginx-proxy:alpine
      <<: *restart
      ports:
        - 80:80
        - 443:443
      volumes:
        # HTTPS certificates
        - ${docker_data_folder}/nginx-proxy/certificates:/etc/nginx/certs:ro
        - ${docker_data_folder}/nginx-proxy/nginx-vhosts:/etc/nginx/vhost.d:ro
        - ${docker_data_folder}/nginx-proxy/nginx-html:/usr/share/nginx/html
        # additional nginx configuration
        - ${docker_data_folder}/nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
        - ${docker_data_folder}/nginx-proxy/.htpasswd:/.htpasswd:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
      labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
      networks:
        - frontend
      security_opt:
        - no-new-privileges
    # letsencrypt container for HTTPS certificate generation
    nginx-letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion:latest
      <<: *restart
      depends_on:
        - "nginx-proxy"
      volumes:
        - ${docker_data_folder}/nginx-proxy/certificates:/etc/nginx/certs:rw
        - ${docker_data_folder}/nginx-proxy/nginx-vhosts:/etc/nginx/vhost.d:rw
        - ${docker_data_folder}/nginx-proxy/nginx-html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        - DHPARAM_BITS=4096
      networks:
        - frontend
      security_opt:
        - no-new-privileges
    # qbittorrent torrent client container
    qbittorrent:
      image: binhex/arch-qbittorrentvpn:latest
      <<: *restart
      privileged: true
      depends_on:
        - "nginx-proxy"
        - "nginx-letsencrypt"
      cap_add:
        - NET_ADMIN
      volumes:
        - ${data_folder}:/data
        - ${torrent_blackhole}:/blackhole
        - ${docker_data_folder}/qbittorrent:/config
        - /etc/localtime:/etc/localtime:ro
      environment:
        <<: *https
        PGID: ${GID}
        PUID: ${UID}
        #UMASK: 007
        VPN_ENABLED: "yes"
        VPN_USER: ${openvpn_user}
        VPN_PASS: ${openvpn_password}
        VPN_PROV: custom
        #VPN_OPTIONS: <additional openvpn cli options>
        STRICT_PORT_FORWARD: "no"
        ENABLE_PRIVOXY: "no"
        LAN_NETWORK: 192.168.0.0/24
        # set DNS to docker DNS, this creates a voluntary DNS leak outside of VPN tunnel
        # note that in some setups this might be unsafe (I recommed using DNScrypt on the host to make this safe)
        # but I have not found another way for qbittorrent to resolve the jackett magnet links passed by hydra
        # which point to jackett's docker DNS name
        NAME_SERVERS: 127.0.0.11
        DEBUG: "false"
        WEBUI_PORT: 8080
        VIRTUAL_HOST: torrent.${root_domain}
        VIRTUAL_PORT: 8080
        LETSENCRYPT_HOST: torrent.${root_domain}
      networks:
        - frontend
        
networks:
  frontend:
```

## Logs

```
(N) 2019-01-05T20:22:38 - Web UI: Now listening on IP: *, port: 8080                                                                                 [452/683]
(I) 2019-01-05T20:22:38 - qBittorrent is successfully listening on interface :: port: TCP/6881                                                                
(I) 2019-01-05T20:22:38 - qBittorrent is successfully listening on interface 0.0.0.0 port: TCP/6881                                                           
(I) 2019-01-05T20:22:38 - qBittorrent is successfully listening on interface 0.0.0.0 port: UDP/6881                                                           
(N) 2019-01-05T20:22:39 - [A TORRENT NAME] restored.                                                                       
(I) 2019-01-05T20:22:40 - External IP: [AN EXTERNAL IP]
(N) 2019-01-05T20:23:35 - WebAPI login success. IP: ::ffff:172.20.0.9
(N) 2019-01-05T20:23:37 - WebAPI login success. IP: ::ffff:172.20.0.5
(N) 2019-01-05T20:23:52 - WebAPI login success. IP: ::ffff:172.20.0.14
(N) 2019-01-05T20:26:35 - Successfully moved torrent: [A TORRENT NAME] New path: /config/qBittorrent/
```

## qbittorrent settings
![screenshot from 2019-01-07 13-46-14](https://user-images.githubusercontent.com/30023543/50769004-746b2600-127a-11e9-8185-18949024517b.png)
