### ISSUE TITLE
Can't work out why connections are being blocked

### ISSUE THREAD

**Issue by Cylindric** [binhex/arch-qbittorrentvpn#291]
Hi folks. I can't work out why my VPN/proxy/qbittorrent isn't quite working. It's a bit odd, because it _has_ worked but stopped at some point in the last couple of weeks and I'm not sure why.

My setup is a depoyment running in a K3s cluster. VPN is ExpressVPN.

```yaml
      containers:
      - name: torrent
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["NET_ADMIN"]
        env:                       # < environment variables. See https://github.com/binhex/arch-qbittorrentvpn
        - name: WEBUI_PORT
          value: "8080"
        - name: NAME_SERVERS
          value: "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1"
        - name: LAN_NETWORK
          value: "172.29.14.0/24"
        - name: ENABLE_PRIVOXY
          value: "yes"
        - name: PGID
          value: "\x31\x30\x30\x31"    # < ASCII code for '1001'
        - name: PUID
          value: "\x31\x30\x30\x31" # < ACII code for '1001'
        - name: UMASK
          value: "\x30\x30\x30" # < ACII code for '000'
        - name: VPN_ENABLED
          value: "yes"
        - name: VPN_CLIENT
          value: openvpn
        - name: VPN_PROV
          value: custom
        - name: VPN_USER
          value: myuser
        - name: VPN_PASS
          value: mypassword
        - name: ENABLE_STARTUP_SCRIPTS
          value: "no"
        - name: STRICT_PORT_FORWARD
          value: "yes"
        - name: USERSPACE_WIREGUARD
          value: "no"
        - name: ENABLE_SOCKS
          value: "yes"
        - name: SOCKS_USER
          value: "admin"
        - name: SOCKS_PASS
          value: "socks"
        - name: VPN_INPUT_PORTS
          value: "1234"
        - name: VPN_OUTPUT_PORTS
          value: "5678"
        - name: DEBUG
          value: "true"
        image: binhex/arch-qbittorrentvpn
        imagePullPolicy: Always
        ports:
        - containerPort: 8118
          name: torrent-proxy
          protocol: TCP
        - containerPort: 8080
          name: torrent-web
          protocol: TCP
```

Here's my OpenVPN config:

```
dev tun
fast-io
persist-key
nobind
remote uk-london-ca-version-2.expressnetw.com 1195
status /config/openvpn/openvpn.status

remote-random
pull
comp-lzo no
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1200
verb 3
cipher AES-256-GCM
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass credentials.conf
<cert>
...
</cert>
```

`ip a` shows the interface is "UNKNOWN"
```
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 10.185.213.133 peer 10.185.213.134/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::49a9:af14:7bae:9b44/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

Does that mean the VPN is up or not? I'm not really sure, and with the layers of routing, firewalling and VPN inside this container, I'm not sure how to determine where the blockage is.

DNS seems to be working, at least name resolution is returning correct addresses.

`curl -v -x admin:socks@localhost:8118 http://google.com` eventually times out, and that looks like the proxy is refusing connections? The privoxy log file is empty.
```
* Host localhost:8118 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8118...
* connect to ::1 port 8118 from ::1 port 52516 failed: Connection refused
*   Trying 127.0.0.1:8118...
* Connected to localhost (127.0.0.1) port 8118
* using HTTP/1.x
* Proxy auth using Basic with user 'admin'
> GET http://www.google.com/ HTTP/1.1
> Host: www.google.com
> Proxy-Authorization: Basic YWRtaW46c29ja3M=
> User-Agent: curl/8.11.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Request completely sent off
```

privoxy config:
```
user-manual /usr/share/doc/privoxy/user-manual/
confdir /config/privoxy
logdir /config/privoxy
actionsfile match-all.action # Actions that are applied to all sites and maybe overruled later on.
actionsfile default.action   # Main actions file
actionsfile user.action      # User customizations
filterfile default.filter
filterfile user.filter      # User customizations
logfile logfile
listen-address :8118
toggle  1
enable-remote-toggle  0
enable-remote-http-toggle  0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 0
forwarded-connect-retries  0
accept-intercepted-requests 0
allow-cgi-request-crunching 0
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
```

Routes:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.185.213.134  128.0.0.0       UG    0      0        0 tun0
0.0.0.0         10.42.0.1       0.0.0.0         UG    0      0        0 eth0
5.157.128.46    10.42.0.1       255.255.255.255 UGH   0      0        0 eth0
10.42.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.42.0.0       10.42.0.1       255.255.0.0     UG    0      0        0 eth0
10.185.0.1      10.185.213.134  255.255.255.255 UGH   0      0        0 tun0
10.185.213.134  0.0.0.0         255.255.255.255 UH    0      0        0 tun0
128.0.0.0       10.185.213.134  128.0.0.0       UG    0      0        0 tun0
172.29.14.0     10.42.0.1       255.255.255.0   UG    0      0        0 eth0
```
