### ISSUE TITLE
/usr/sbin/wg-quick: line 40: /config/wireguard/wg0.conf: Permission denied

### ISSUE THREAD

**Issue by ericarthurc** [binhex/arch-qbittorrentvpn#315]
Here is my yaml file

```yaml
services:
  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrentvpn
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "9080:9080"
      - "8118:8118"
      - "9118:9118"
      - "58946:58946"
      - "58946:58946/udp"
    volumes:
      - ./data:/data
      - ./data/config:/config
      - ./data/etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=*******
      - VPN_PASS=********
      - VPN_PROV=pia
      - VPN_CLIENT=wireguard
      - ENABLE_STARTUP_SCRIPTS=no
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=yes
      - SOCKS_USER=admin
      - SOCKS_PASS=socks
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - WEBUI_PORT=9080
      - UMASK=000
      - PUID=0
      - PGID=0
    network_mode: bridge
    restart: unless-stopped
```

The wg0.conf file is generated where I have the volumes specificied, and it looks like this:

```md
[Interface]
Address = 10.26.171.47
PrivateKey = ************
PostUp = '/root/wireguardup.sh'
PostDown = '/root/wireguarddown.sh'

[Peer]
PublicKey = **************
AllowedIPs = 0.0.0.0/0
Endpoint = nl-amsterdam.privacy.network:1337
```

But I am getting this error on startup:

```bash
2025-04-22 19:30:07,692 DEBG 'start-script' stdout output:
[info] Configuring WireGuard...

2025-04-22 19:30:07,900 DEBG 'start-script' stdout output:
[info] Token generated for PIA wireguard authentication

2025-04-22 19:30:07,905 DEBG 'start-script' stdout output:
[info] Trying to connect to the PIA WireGuard API on 'nl-amsterdam.privacy.network'...

2025-04-22 19:30:08,539 DEBG 'start-script' stdout output:
[info] Attempting to bring WireGuard interface 'up'...

2025-04-22 19:30:08,549 DEBG 'start-script' stderr output:
Warning: `/config/wireguard/wg0.conf' is world accessible

2025-04-22 19:30:08,549 DEBG 'start-script' stderr output:
/usr/sbin/wg-quick: line 40: /config/wireguard/wg0.conf: Permission denied

2025-04-22 19:30:08,550 DEBG 'start-script' stdout output:
[warn] WireGuard interface failed to come 'up', exit code is '1'
```

Not really sure what to do here?? I also tried with - PUID=1000 and - PGID=1000, but the same issue.

**Comment by klinker41** [comment]
I'm also experiencing this issue after upgrading to Ubuntu 25.04. I've tried modifying the permissions for my config directory to allow anyone to modify, changed the PUID and PGID to the appropriate values, etc, but have not found a solution.

**Comment by ericarthurc** [comment]
> I'm also experiencing this issue after upgrading to Ubuntu 25.04. I've tried modifying the permissions for my config directory to allow anyone to modify, changed the PUID and PGID to the appropriate values, etc, but have not found a solution.

I ended up switching to a whole new docker image and setup.

```yml
gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-bit
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_REGIONS=US California
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./data:/config
      - /mnt/seagate-mirror-pool/raid-shares/Torrents:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
```
