### ISSUE TITLE
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted

### ISSUE THREAD

**Issue by Demon-tk** [binhex/arch-qbittorrentvpn#73]
Hello, I am receiving a fatal error when running the image.

Here is my docker-compose.yml file: 
```yaml
---
version: "2.1"
services:
    apps:
        image: binhex/arch-qbittorrentvpn
        container_name: qbitvpn
        #--cap-add=NET_ADMIN
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8081:8080
            - 8118:8118
        #--name=qbittorrentvpn
        volumes:
            - S:\My Files\Torrents:/data
            - S:\My Files\Docker\qbitvpn\config:/config
            #- /etc/localtime:/etc/localtime:ro
        environment:
            - VPN_ENABLED=yes
            - VPN_PROV=airvpn
            - VPN_CLIENT=openvpn
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=10.0.0.1/24
            - NAME_SERVERS=1.1.1.1,1.0.0.1,9.9.9.9,8.8.8.8
            - ADDITIONAL_PORTS=1234
            - DEBUG=false
            - WEBUI_PORT=8080
            - UMASK=000
            - PUID=0
            - PGID=0
        restart: unless-stopped
```

The error log is way too long to post here so I have a Gist linked here:
```
https://gist.github.com/Demon-tk/30aa04bf6e54741ed59b9ea540edf7c7
```

I have not yet configured `/config/qBittorrent` as I cant run the container yet but I have forwarded my Airvpn port via the client panel.

Any ideas what might be going on?

**Comment by binhex** [comment]
``` #--cap-add=NET_ADMIN```

why is this commented out?, this is most likely your issue.

**Comment by Demon-tk** [comment]
> ` #--cap-add=NET_ADMIN`
> 
> why is this commented out?, this is most likely your issue.

Hello,

I removed it because it threw an error. I am unsure how to properly write the config for this line in docker-compose, would it look like this:

```yaml
securityContext:
            capabilities:
                drop: ["all"]
                add: ["NET_BIND"]
```

Upon running this I receive an error:
```
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
Unsupported config option for services.apps: 'securityContext'
```

**Comment by binhex** [comment]
no idea on compose, sorry, but you def need it.

**Comment by Demon-tk** [comment]
Okay, that did seem to fix this issue, which is odd because I could not find it in any docs.

For anyone that might want to use docker-compose (which is the recommended method) you should be able to use the config below:

```yaml
---
version: "2.1"
services:
    apps:
        image: binhex/arch-qbittorrentvpn
        container_name: qbitvpn
            - NET_ADMIN
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
            - 8118:8118
        #--name=qbittorrentvpn
        volumes:
            - [data map]:/data
            - [config map]:/config
            #- /etc/localtime:/etc/localtime:ro
        environment:
            - VPN_ENABLED=yes
            - VPN_PROV=airvpn
            - VPN_CLIENT=openvpn
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=10.0.0.1/24
            - NAME_SERVERS=1.1.1.1,1.0.0.1,9.9.9.9
            - ADDITIONAL_PORTS=1234
            - DEBUG=false
            - WEBUI_PORT=8080
            - UMASK=000
            - PUID=0
            - PGID=0
        restart: unless-stopped
   ```
