### ISSUE TITLE
Unable to access port 8080 on host

### ISSUE THREAD

**Issue by Demon-tk** [binhex/arch-qbittorrentvpn#74]
I am unable to connect to the [host]:8080 on my Ubuntu server. I used my docker-compose config here which works on my local machine but not my server: https://gist.github.com/Demon-tk/acc2890f16587c2a761ddf758c6a321f.

The docker container is running and does say that the qBittorrent process is listening on port 8080. I am able to connect to the Ubuntu server, as well as my other applications on there, but not this one as seen here: https://i.imgur.com/DTtI7z4.png

Here is the log file for the container: https://gist.github.com/Demon-tk/5b0b925bd5f3229208b4c56ecd853807. 

A telnnet of the host shows that it will accept the connection then immediatly close it, which leads me to believe that there is some application error I am unaware of.

```
$ telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

If anyone knows what is up please let me know.

**Comment by nicklayb** [comment]
I have a similar issue. If use `wget` to get the page it returns me the correct HTML.

Using firefox it tries to download it as an `application/octet-stream` that contains the HTML and with Chrome it just displays the HTML in the page.
  
```yaml
version: '3'
services:
  qbittorrent:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorent-vpn
    network_mode: bridge
    volumes:
      - /media/torrent/qbittorent:/data
      - ./qbittorent_config:/config
      - /etc/localtime:/etc/localtime:ro
    env_file: .qbittorrent.env
    ports:
        - "8088:8088"
        - "6881:6881"
        - "6881:6881/udp"
        - "8128:8118"
    cap_add:
        - NET_ADMIN
    labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:myhost"
        - "traefik.port=8088"      
``` 

My env: 
```
VPN_ENABLED=yes
VPN_PROV=airvpn
VPN_CLIENT=openvpn

ENABLE_PRIVOXY=yes

LAN_NETWORK=192.168.1.0/24
NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1

DEBUG=true

UMASK=000
PUID=1000
GUID=1000

WEBUI_PORT=8088
```

Weird thing is that in the log if have the following looping over and over again
```
2021-02-25 22:40:03,226 DEBG 'watchdog-script' stdout output:
[debug] Checking we can resolve name 'www.google.com' to address...

2021-02-25 22:40:03,244 DEBG 'watchdog-script' stdout output:
[debug] DNS operational, we can resolve name 'www.google.com' to address '172.217.0.228'

2021-02-25 22:40:03,245 DEBG 'watchdog-script' stdout output:
[debug] Waiting for iptables chain policies to be in place...

2021-02-25 22:40:03,259 DEBG 'watchdog-script' stdout output:
[debug] iptables chain policies are in place

2021-02-25 22:40:03,275 DEBG 'watchdog-script' stdout output:
[debug] VPN IP is xxx.xxx.xxx.xxx
[debug] qBittorrent IP is xxx.xxx.xxx.xxx
```

This is a fresh install, only thing I did is copy my openvpn file to the configs. The LAN_NETWORK really represents my local network.
