### ISSUE TITLE
cannot generate PIA token anymore

### ISSUE THREAD

**Issue by ljmerza** [binhex/arch-qbittorrentvpn#86]
started yesterday, dont see anything about outages.

```
2021-04-16 09:39:19,363 DEBG 'start-script' stdout output:
[warn] Unable to successfully download PIA json to generate token from URL 'https://212.102.35.130/authv3/generateToken'
[info] Retrying in 10 secs...
```

**Comment by tezgno** [comment]
Same issue. Started day before yesterday for me.

**Comment by tezgno** [comment]
Reverting back to 4.3.3-1-05 seems to resolve the issue for me. Something related to 4.3.3-1-06 and PIA is causing issues.

**Comment by ljmerza** [comment]
I tried that and it didn't work for me. The only difference between 05 and 06 is adding binding on the qbittorrent port so I don't think the version change itself fixed it and you got lucky.

**Comment by sklm** [comment]
Try downloading and replacing the latest PIA openvpn files.

**Comment by tezgno** [comment]
> Try downloading and replacing the latest PIA openvpn files.

We are connecting using Wireguard

**Comment by ljmerza** [comment]
just tried that and it didnt work. here's my docker compose

```
qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn:4.3.3-1-06
    env_file: env/qbittorrentvpn.env
    restart: always
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8118:8118
      - 8087:8087
    volumes:
      - /home/user/docker:/config
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    privileged: true
```

```
TZ=America/New_York

PUID=1000
PGID=1000

VPN_ENABLED=yes
VPN_CLIENT=wireguard
VPN_USER=xxx
VPN_PASS=xxx
VPN_PROV=pia

STRICT_PORT_FORWARD=yes
ENABLE_PRIVOXY=yes
DEBUG=true
WEBUI_PORT=8087
```
