### ISSUE TITLE
privoxy proxy not responding outside of the pod

### ISSUE THREAD

**Issue by lealoureiro** [binhex/arch-qbittorrentvpn#98]
Hello!

First of all thanks for great work!

I'm currently running this image in k8s with OpenVPN which seems to work fine and able to download via qBitTorrent with VPN connected.

But i'm having problems to use the privoxy outside of the pod.

When I do a test curl inside the c pod it works:
```shell
[root@qbittorrent-vpn-689f6d78c7-f8drs privoxy]# curl http://localhost:8118
Invalid header received from client.
```

But when I do outside of the pod, in another pod in same namespace, does not work:
```shell
root@jackett-df4576956-mbcqs:/# curl http://qbittorrent-vpn:8118
^C

```
From same pod I can access the ui interface:
```shell
root@jackett-df4576956-mbcqs:/# curl http://qbittorrent-vpn:8080
<!DOCTYPE html>
<html lang="en">

<head>

```

Watching the 8118 port on qbittorrent-vpn, seems to be listen in all interfaces:
```shell
[root@qbittorrent-vpn-689f6d78c7-f8drs privoxy]# netstat -an | grep 8118
tcp        0      0 0.0.0.0:8118            0.0.0.0:*               LISTEN
```

I have the env variable defined as this:
```yaml
        - name: ENABLE_PRIVOXY
          value: "yes"
        - name: LAN_NETWORK
          value: "172.16.0.0/16, 10.96.0.0/12, 192.168.178.0/24"
```
